FROM node:22 AS builder

WORKDIR /frontend

COPY package*.json ./
RUN yarn install

COPY . .
RUN yarn build

FROM node:22

WORKDIR /frontend

RUN npm install -g serve

COPY --from=builder /frontend/dist ./dist
COPY --from=builder /frontend/package*.json ./

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]